version: '3'
services:
  user-service:
    container_name: user-service
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/main/resources:/src/main/resources
    ports:
      - "8081:8081"
    restart: always